name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Upgrade pip and nox
      run: |
        pip install --upgrade pip nox
        pip --version
        nox --version

    - name: Build package
      run: nox -s build

    - name: Upload package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
