name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        pyv: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.pyv }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyv }}

    - name: Upgrade pip and nox
      run: |
        python -m pip install --upgrade pip nox
        pip --version
        nox --version

    - name: Lint code and check dependencies
      run: nox -s lint safety

    - name: Run tests
      env:
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID}}
        OSS_SECRET_ACCESS_KEY: ${{ secrets.OSS_SECRET_ACCESS_KEY}}
        OSS_TEST_STS_ID: ${{ secrets.OSS_TEST_STS_ID}}
        OSS_TEST_STS_KEY: ${{ secrets.OSS_TEST_STS_KEY}}
        OSS_TEST_STS_ARN: ${{ secrets.OSS_TEST_STS_ARN}}
        OSS_ENDPOINT: ${{ vars.OSS_ENDPOINT}}
        OSS_TEST_BUCKET_NAME: ${{ vars.OSS_TEST_BUCKET_NAME}}
        OSS_TEST_ANONYMOUS_BUCKET_NAME: ${{ vars.OSS_TEST_ANONYMOUS_BUCKET_NAME}}
      run: nox -s tests-${{ matrix.nox_pyv || matrix.pyv }} -- --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3.1.1

    - name: Build package
      run: nox -s build
